name: hexpm-release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Publish to hex.pm
        run: rebar3 hex publish --repo hexpm --yes --without-docs
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
